### ISSUE TITLE
Wrong license on npm

### ISSUE THREAD

**Issue by aurbano** [JackuB/diff-match-patch#10]
The version released on npm as 1.0.0 has `http://www.apache.org/licenses/LICENSE-2.0` in the [license field](https://github.com/JackuB/diff-match-patch/blob/1.0.0/package.json#L17), which has been fixed in master ("Apache-2.0")

This means that tools for automated license verification of dependencies fail on this package, as they can't recognise the exact license used.

Could you release a new version in npm with the contents of master?

**Comment by JackuB** [comment]
Hey, sorry I missed this issue! I took over this repo, but forgot to Watch it :-|

Released https://github.com/JackuB/diff-match-patch/releases/tag/1.0.1 with a proper license

**Comment by aurbano** [comment]
Thanks!
