### ISSUE TITLE
Can't instantiate DiffMatchPatch

### ISSUE THREAD

**Issue by domessina** [JackuB/diff-match-patch#15]
**Hello, I can't use the object DiffMatchPatch. Here is my code**

import {Component, Input, OnInit} from '@angular/core';
import {ActService} from "../../../../services/act.service";
import {DialogService} from "../../../../dialog-service/dialog.service";
import {Router} from "@angular/router";
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/forkJoin';
import DiffMatchPatch from 'diff-match-patch';
const dmp = new DiffMatchPatch();

@Component({
  selector: 'act-step-content-validation',
  templateUrl: './act-step-content-validation.component.html',
  styleUrls: ['./act-step-content-validation.component.css']
})
export class ActStepContentValidationComponent implements OnInit {

  @Input() metadata;
  public loading: boolean = false;
  public previewModifications;
  public previewImport;

  constructor(private actService: ActService, 
              private dialogService: DialogService) {
  }

  ngOnInit() {

    this.loading = true;
    this.actId = this.metadata.id;

    Observable.forkJoin([
      this.actService.getWorkingActPreview(this.metadata.id.value, "10-10-2018"),
      this.actService.getImportedActPreview(this.metadata.id.value)
    ])
      .subscribe(([wP, iP]) => {
      this.previewModifications = wP;
      this.previewImport = iP;
        dmp.Diff_Timeout = 0;
        let diffOutput = dmp.diff_main(this.previewModifications, this.previewImport, false);
        console.log(diffOutput);
      });
  }

**Here is the error** : ![image](https://user-images.githubusercontent.com/17341400/48213979-430bd200-e37f-11e8-84f7-523528a91737.png)

What's wrong ? thank you

**Comment by JackuB** [comment]
What version is that? 1.0.4?

**Comment by domessina** [comment]
Thank you for your answer but  we moved to another library now. [https://www.npmjs.com/package/ng-diff-match-patch]
