### ISSUE TITLE
Boilerplate in License

### ISSUE THREAD

**Issue by curiositycasualty** [JackuB/diff-match-patch#23]
https://github.com/JackuB/diff-match-patch/blob/bed54bb6920d51cab3b52bf407216b343473a622/LICENSE#L190

**Comment by JackuB** [comment]
Thank you for raising this! The license file is a carbon copy of the upstream one https://github.com/google/diff-match-patch/blob/master/LICENSE but I'll update the notice in this repo.

I won't be releasing a new minor version to the npm with this change. But it will eventually be included in future releases.
