### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by batir-akhmerov** [JackuB/diff-match-patch#24]
We have been receiving the following error:
`index.js:2214 Uncaught ReferenceError: module is not defined
    at index.js:2214:1`

Steps to replicate: 

- run **npm install diff-match-patch**
- import index.js in the main app '/node_modules/diff-match-patch/index.js', which is added to the plain `<script type="text/javascript" charset="UTF-8" src="http://localhost:1962/node_modules/diff-match-patch/index.js"></script>`

**Comment by JackuB** [comment]
Hey, what you are seeing is a result of the way [JavaScript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) works. 

This library is using an older CommonJS syntax (`module.exports`):

https://github.com/JackuB/diff-match-patch/blob/b51e1044a688503d3c299a7b14a6eaf9d59c75d3/index.js#L2213-L2218

CommonJS is supported by Node.js, but not supported by web browsers.

If you want to use this CommonJS library in a browser, you might need to have a build step in your application that will transform this module from CommonJS modules to a module compatible with a browser. I'd recommend looking into for example Webpack or Rollup.

Or if you want, a lo-fi solution, you could also modify the library on your disk, removing the `module.exports` lines from the `index.js` and then trating the diff_match functions as global.

**Comment by batir-akhmerov** [comment]
At a quick glance there are no other CommonJS dependencies in the code. So, possibly, simple `module = module || {};` on line 2213 could save the hassle and make this library flexible enough to work in the browser out of the box.
