### ISSUE TITLE
Possible diff miss-match between JavaScript and C++

### ISSUE THREAD

**Issue by jcalfee** [JackuB/diff-match-patch#4]
Under heavy use, we create patches in JavaScript and apply them in C++.  User's may use blockquote `>`  but occasionally the C++ will try to apply this patch but get an error.

Here are some reports: https://github.com/steemit/steemit.com/issues/37

Since we use the npm 1.0.0 version, can you let me know if there are any changes to Google's original version that might cause this?

http://code.google.com/p/google-diff-match-patch/
diff_match_patch_20121119.zip

**Comment by JackuB** [comment]
Compared the canonical version from Google code and haven't found any changes. Is this still relevant @jcalfee? I could look closer into the diffing if you have some failing/mismatched examples

**Comment by jcalfee** [comment]
Probably not an issue at all..  The original issue involves complex logic so it was probably a problem there..
